In [1]:
import numpy as np

In [2]:
import array

In [5]:
np.array([10,20,"tiki",4+9j,30])

array(['10', '20', 'tiki', '(4+9j)', '30'], dtype='<U64')

In [4]:
type(np.array([10,20,30]))

numpy.ndarray

In [6]:
np.array([10,20.0,30])

array([10., 20., 30.])

In [7]:
np.array([[1,2],[4,5]])

array([[1, 2],
       [4, 5]])

In [8]:
np.array([[1,2],[4,5],[6,7,8]])

C:\Users\lenovo\AppData\Local\Temp\ipykernel_10744\2902397712.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2],[4,5],[6,7,8]])


array([list([1, 2]), list([4, 5]), list([6, 7, 8])], dtype=object)

In [10]:
np.array([[[1,2],[4,5]],[[5,6],[2,3]]])

array([[[1, 2],
        [4, 5]],

       [[5, 6],
        [2, 3]]])

In [13]:
np.array([4,5,6,7],ndmin=5)

array([[[[[4, 5, 6, 7]]]]])

In [15]:
np.array([4,7,8,9],dtype=complex)

array([4.+0.j, 7.+0.j, 8.+0.j, 9.+0.j])

In [16]:
np.array([(1,2),(6,7)])

array([[1, 2],
       [6, 7]])

In [18]:
arr=np.array([(1,2),(6,7)],dtype=[('a','<i2'),('b','<i8')])

In [21]:
type(arr[0][0])

numpy.int16

In [25]:
type(arr[0][1])

numpy.int64

In [30]:
arr1=np.array([(1,2),(6,7)],dtype=[('a','<i4'),('b','<i8')])

In [31]:
type(arr1[0][0])

numpy.int32

In [34]:
arr2=np.array([(2,3),(3,7)])

In [35]:
arr2

array([[2, 3],
       [3, 7]])

In [39]:
arr2[1][0]

3

In [41]:
type(arr2[1][0])

numpy.int32

In [42]:
np.mat(arr2)

matrix([[2, 3],
        [3, 7]])

In [43]:
l=[3,4,5,6,7]

In [44]:
np.array(l)

array([3, 4, 5, 6, 7])

In [45]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [46]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [49]:
mat=np.matrix(arr2)

In [50]:
np.asanyarray(mat)

matrix([[2, 3],
        [3, 7]])

In [51]:
np.asarray(mat)

array([[2, 3],
       [3, 7]])

In [55]:
issubclass(np.matrix,np.ndarray) #matrix is subclass of ndarray

True

In [56]:
issubclass(np.ndarray,np.matrix) #ndarray is not subclass of matrix

False

In [59]:
arr2

array([[2, 3],
       [3, 7]])

In [68]:
a=arr2 #shallow copy

In [69]:
b=np.copy(arr2) #deep copy

In [70]:
b

array([[20,  3],
       [ 3,  7]])

In [71]:
a

array([[20,  3],
       [ 3,  7]])

In [73]:
arr2[0][0]=120

In [74]:
arr2

array([[120,   3],
       [  3,   7]])

In [75]:
a

array([[120,   3],
       [  3,   7]])

In [76]:
b

array([[20,  3],
       [ 3,  7]])

In [77]:
arr2[-1]

array([3, 7])

In [78]:
for i in arr2:
    print(i)

[120   3]
[3 7]


In [81]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [82]:
type(np.fromfunction(lambda i,j:i==j,(3,3)))

numpy.ndarray

In [84]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [85]:
np.fromfunction(lambda i,j:i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [86]:
np.fromfunction(lambda i,j:i/j,(3,3))

C:\Users\lenovo\AppData\Local\Temp\ipykernel_10744\224034625.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j:i/j,(3,3))
C:\Users\lenovo\AppData\Local\Temp\ipykernel_10744\224034625.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j:i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])